import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={""}>
          <div className="flex h-screen bg-gray-100">
            {/* <Sidebar /> */}

            <div className="flex-1 flex flex-col">
              {/* <Navbar /> */}

              <main className="">{children}</main>
            </div>
          </div>{" "}
        
      </body>
    </html>
  );
}
